name: PEP8
on:
  pull_request:

  workflow_dispatch:

jobs:
  check_pep8:
    runs-on: ubuntu-latest

    steps:
      
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
