name: PEP8
on: [push, pull_request]
jobs:
  formatting-check:
    name: PEP8 Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Проверка форматирования
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose
